import * as path from 'path';
import { DelphiLSPConfig, loadConfigFileJson } from '../client/configFile';
import { Uri, window, workspace } from 'vscode';

// Static on purpose: all project-specific values are passed as parameters, never interpolated.
const RUN_SCRIPT = `# Generated by the Delphi extension. Regenerated automatically; local edits are overwritten.
param(
    [Parameter(Mandatory = $true)][string]$BinDir,
    [Parameter(Mandatory = $true)][string]$Project,
    [string]$ExePath,
    [switch]$Run
)

# Import the RAD Studio build environment from rsvars.bat (plain SET statements).
Get-Content -LiteralPath (Join-Path $BinDir 'rsvars.bat') | ForEach-Object {
    if ($_ -match '^\\s*@?SET\\s+([^=]+)=(.*)$') {
        $value = [regex]::Replace($Matches[2], '%([^%]+)%', {
            param($m) [Environment]::GetEnvironmentVariable($m.Groups[1].Value)
        })
        [Environment]::SetEnvironmentVariable($Matches[1].Trim(), $value, 'Process')
    }
}

& (Join-Path $env:FrameworkDir 'MSBuild.exe') $Project '/t:Clean,Make'

if ($LASTEXITCODE -ne 0) {
    Write-Host "Build failed with exit code $LASTEXITCODE"
    exit $LASTEXITCODE
}

Write-Host ''

if (-not $Run) {
    exit 0
}

Write-Host "Running $ExePath..."
$process = Start-Process -FilePath $ExePath -PassThru
Wait-Process -Id $process.Id
`;

/**
 * Path of the run script in the first workspace folder.
 *
 * @returns script URI, or undefined if no folder is open
 */
export function getRunScriptUri(): Uri | undefined {
    const folder = workspace.workspaceFolders?.[0];
    return folder ? Uri.joinPath(folder.uri, '.vscode', 'delphi', 'scripts', 'run.ps1') : undefined;
}

/**
 * Resolves the MSBuild project and output executable for an LSP config.
 *
 * @param settings settings of the loaded LSP config
 * @returns project directory, .dproj path and executable path
 */
export function resolveProjectPaths(settings: DelphiLSPConfig['settings']) {
    const projectDir = path.dirname(settings.project);
    const projectName = path.parse(settings.project).name;
    const outputDir = /(?:^|\s)-E(?:"([^"]*)"|(\S*))/.exec(settings.dccOptions);
    const exeDir = outputDir?.[1] ?? outputDir?.[2] ?? '';
    return {
        projectDir,
        dproj: path.join(projectDir, projectName + '.dproj'),
        exePath: path.resolve(projectDir, exeDir, projectName + '.exe'),
    };
}

/**
 * Writes the run script to .vscode/delphi/scripts in the current workspace when an LSP config is set.
 *
 * @param config optional LSP config URI, defaults to the configured one
 * @returns true if the script was written
 */
export async function initRunScript(config?: string): Promise<boolean> {
    const scriptUri = getRunScriptUri();
    if (!scriptUri) return false;
    const json = await loadConfigFileJson(config);
    if (json === false) return false; // No config file has been set

    try {
        await workspace.fs.createDirectory(Uri.joinPath(scriptUri, '..'));
        await workspace.fs.writeFile(scriptUri, Buffer.from(RUN_SCRIPT));
    } catch (e) {
        window.showErrorMessage(`Delphi: Could not write run script "${scriptUri.fsPath}": ${e}`);
        return false;
    }
    return true;
}
